export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "surface-tint": "#565e74",
              "secondary-fixed": "#d5e3fd",
              "surface-container": "#eceef0",
              "surface-container-highest": "#e0e3e5",
              "primary-fixed": "#dae2fd",
              "surface": "#f7f9fb",
              "on-error": "#ffffff",
              "primary-container": "#131b2e",
              "inverse-on-surface": "#eff1f3",
              "primary": "#000000",
              "on-tertiary-fixed-variant": "#003ea8",
              "surface-bright": "#f7f9fb",
              "on-tertiary": "#ffffff",
              "metric-blue": "#EFF6FF",
              "border-subtle": "#E2E8F0",
              "primary-fixed-dim": "#bec6e0",
              "on-primary": "#ffffff",
              "tertiary": "#000000",
              "on-primary-fixed-variant": "#3f465c",
              "on-error-container": "#93000a",
              "academic-navy": "#0F172A",
              "error-container": "#ffdad6",
              "on-background": "#191c1e",
              "outline": "#76777d",
              "secondary-container": "#d5e3fd",
              "outline-variant": "#c6c6cd",
              "tertiary-fixed-dim": "#b4c5ff",
              "tertiary-fixed": "#dbe1ff",
              "on-secondary": "#ffffff",
              "on-secondary-fixed": "#0d1c2f",
              "surface-container-lowest": "#ffffff",
              "on-secondary-container": "#57657b",
              "on-tertiary-container": "#497cff",
              "tertiary-container": "#00174b",
              "surface-container-low": "#f2f4f6",
              "secondary-fixed-dim": "#b9c7e0",
              "on-primary-container": "#7c839b",
              "error": "#ba1a1a",
              "on-surface-variant": "#45464d",
              "on-tertiary-fixed": "#00174b",
              "on-primary-fixed": "#131b2e",
              "on-secondary-fixed-variant": "#3a485c",
              "surface-dim": "#d8dadc",
              "inverse-primary": "#bec6e0",
              "surface-container-high": "#e6e8ea",
              "secondary": "#515f74",
              "on-surface": "#191c1e",
              "surface-variant": "#e0e3e5",
              "background": "#f7f9fb",
              "inverse-surface": "#2d3133",
              "slate-gray": "#64748B"
          },
          "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
          },
          "spacing": {
              "stack-sm": "8px",
              "stack-md": "16px",
              "container-max": "1120px",
              "section-gap-lg": "8rem",
              "stack-lg": "32px",
              "section-gap-md": "4rem",
              "gutter": "24px"
          },
          "fontFamily": {
              "metric-value": ["Inter"],
              "label-mono": ["JetBrains Mono"],
              "subhead-bold": ["Inter"],
              "display-hero": ["Inter"],
              "body-secondary": ["Inter"],
              "headline-section": ["Inter"],
              "display-hero-mobile": ["Inter"],
              "body-main": ["Inter"]
          },
          "fontSize": {
              "metric-value": ["36px", {"lineHeight": "44px", "fontWeight": "700"}],
              "label-mono": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
              "subhead-bold": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
              "display-hero": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "body-secondary": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "headline-section": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "display-hero-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
              "body-main": ["16px", {"lineHeight": "26px", "fontWeight": "400"}]
          }
      }
  },
  plugins: [],
}
